name = input('What is your name?\n')
print('Hello, %s.' % name)
robot = input('Are you a robot? Write yes or no\n')
print('Robot or Not: %s' % robot)
feel = input('How do you feel?\n')
print('Ok you feel, %s.' % feel)
print('Ok that is the ending of Demo Python ChatBot')
bye = input('Say bye\n')
print('ENDED WITH BYE COMMAND: %s' % bye)