name = input('What is your name?\n')
print('Hi, %s.' % name)
feel = input('How do you feel?\n')
print('Ok you feel, %s.' % feel)
robot = input('Are you robot? Write yes or no\n')
print('Robot or Not: %s' % robot)